- name: Mysql | Install Mysql
  sudo: yes
  action: apt pkg=$item
  with_items:
    - mysql-server
    - python-mysqldb

- name: Mysql | Setup mysql database
  sudo: yes
  mysql_db: name=app state=present

- name: Mysql | Add mysql user
  sudo: yes
  mysql_user: name=app priv=app.*:ALL password=${access_token}
