- name: Postgresql | Install postgresql
  sudo: yes
  action: apt pkg=$item state=$postgresql_state
  with_items:
  - postgresql
  - postgresql-contrib

- name: Postgresql | Setup postgresql database
  when: postgresql_state == "present"
  sudo: yes
  sudo_user: postgres
  postgresql_db: db=$postgresql_db
                 encoding='UTF-8'
                 lc_collate='en_US.UTF-8'
                 lc_ctype='en_US.UTF-8'
                 template='template0'

- name: Postgresql | Add postgresql user
  when: postgresql_state == "present"
  sudo: yes
  sudo_user: postgres
  postgresql_user: name=$postgresql_user
                   db=$postgresql_db
                   password=$postgresql_password
                   role_attr_flags=CREATEDB,NOSUPERUSER